/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyFirstNeuronalNetwork;

import org.neuroph.core.NeuralNetwork;
import org.neuroph.core.data.DataSet;
import org.neuroph.core.data.DataSetRow;
import org.neuroph.nnet.Perceptron;

public class Library {

	public double[] someLibraryMethod(double x, double y) {
		NeuralNetwork neuralNetwork = new Perceptron(2, 1);
		DataSet trainingSet = new DataSet(2, 1);
		trainingSet.add(new DataSetRow(new double[] { 0, 0 }, new double[] { 0 }));
		trainingSet.add(new DataSetRow(new double[] { 0, 1 }, new double[] { 1 }));
		trainingSet.add(new DataSetRow(new double[] { 1, 0 }, new double[] { 1 }));
		trainingSet.add(new DataSetRow(new double[] { 1, 1 }, new double[] { 1 }));
		neuralNetwork.learn(trainingSet);
//		neuralNetwork.save("or_perceptron.nnet");
//		neuralNetwork = NeuralNetwork.createFromFile("or_perceptron.nnet");
		neuralNetwork.setInput(x, y);
		neuralNetwork.calculate();
		return neuralNetwork.getOutput();
	}

}
